
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mang Arblu
 */
public class FrameVolume extends javax.swing.JFrame {

    /**
     * Creates new form FrameVolume
     */
    public FrameVolume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextFieldTinggi = new javax.swing.JTextField();
        TextFieldPanjang = new javax.swing.JTextField();
        TextFieldLebar = new javax.swing.JTextField();
        buttonHitung = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TextFieldSisi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buttonHitung2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TextFieldJariJari = new javax.swing.JTextField();
        buttonHitung3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("The Bold Font", 0, 12)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 260, 50);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("Masukkan Tinggi    :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 120, 140, 50);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("Masukkan Panjang :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 20, 140, 50);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setText("Masukkan Lebar     :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 70, 140, 50);

        TextFieldTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTinggiActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldTinggi);
        TextFieldTinggi.setBounds(180, 130, 180, 40);

        TextFieldPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPanjangActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldPanjang);
        TextFieldPanjang.setBounds(180, 30, 180, 40);

        TextFieldLebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldLebarActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldLebar);
        TextFieldLebar.setBounds(180, 80, 180, 40);

        buttonHitung.setText("Hitung Volume");
        buttonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitungActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHitung);
        buttonHitung.setBounds(100, 180, 190, 30);

        jLabel5.setFont(new java.awt.Font("The Bold Font", 1, 12)); // NOI18N
        jLabel5.setText("Volume Balok");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 0, 90, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("Masukkan Panjang Sisi :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 70, 140, 60);

        TextFieldSisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSisiActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldSisi);
        TextFieldSisi.setBounds(190, 80, 180, 40);

        jLabel7.setFont(new java.awt.Font("The Bold Font", 1, 12)); // NOI18N
        jLabel7.setText("Volume KubUS");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(150, 10, 90, 30);

        buttonHitung2.setText("Hitung Volume");
        buttonHitung2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitung2ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonHitung2);
        buttonHitung2.setBounds(100, 170, 190, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("The Bold Font", 1, 12)); // NOI18N
        jLabel8.setText("Volume Bola");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(150, 10, 90, 30);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel9.setText("Masukkan Jari-Jari :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 70, 140, 60);

        TextFieldJariJari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldJariJariActionPerformed(evt);
            }
        });
        jPanel3.add(TextFieldJariJari);
        TextFieldJariJari.setBounds(190, 80, 180, 40);

        buttonHitung3.setText("Hitung Volume");
        buttonHitung3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitung3ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonHitung3);
        buttonHitung3.setBounds(100, 170, 190, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 400, 250);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldLebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldLebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldLebarActionPerformed

    private void TextFieldTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTinggiActionPerformed

    private void TextFieldPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPanjangActionPerformed

    private void buttonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitungActionPerformed
        int tfPanjang = Integer.parseInt(TextFieldPanjang.getText());
        int tfLebar = Integer.parseInt(TextFieldLebar.getText());
        int tfTinggi = Integer.parseInt(TextFieldTinggi.getText());
        int VolumeBalok = tfPanjang * tfLebar * tfTinggi;
        
        try 
        {
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah :" + VolumeBalok, "Volume", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error :" +e, "Gagal", JOptionPane.WARNING_MESSAGE);    
        }
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_buttonHitungActionPerformed

    private void TextFieldSisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSisiActionPerformed

    private void buttonHitung2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitung2ActionPerformed
        int tfSisi = Integer.parseInt(TextFieldSisi.getText());
        int VolumeKubus = tfSisi*tfSisi*tfSisi;
         
        try 
        {
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah :" + VolumeKubus, "Volume", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error :" +e, "Gagal", JOptionPane.WARNING_MESSAGE);    
        }// TODO add your handling code here:
    }//GEN-LAST:event_buttonHitung2ActionPerformed

    private void TextFieldJariJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldJariJariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldJariJariActionPerformed

    private void buttonHitung3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitung3ActionPerformed
        int tfJariJari = Integer.parseInt(TextFieldJariJari.getText());
        float VolumeBola = (float) (4/3*3.14*tfJariJari*tfJariJari*tfJariJari);
          
        try 
        {
            JOptionPane.showMessageDialog(null, "Volume Bola Adalah :" + VolumeBola, "Volume", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error :" +e, "Gagal", JOptionPane.WARNING_MESSAGE);    
        }// TODO add your handling code here:
    }//GEN-LAST:event_buttonHitung3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVolume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldJariJari;
    private javax.swing.JTextField TextFieldLebar;
    private javax.swing.JTextField TextFieldPanjang;
    private javax.swing.JTextField TextFieldSisi;
    private javax.swing.JTextField TextFieldTinggi;
    private javax.swing.JButton buttonHitung;
    private javax.swing.JButton buttonHitung2;
    private javax.swing.JButton buttonHitung3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
